### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [SimplyDanny/modelica-language-vscode#6]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by brianking** [comment]
@SimplyDanny @lochel 

**Claiming ownership of the namespace for your extension(s)**. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access
As owner you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces. Note that publishing can be done by any contributor to the extension, namely those you add as namespace members once they have signed the Publisher Agreement as well.

**Comment by SimplyDanny** [comment]
The Eclipse Publisher Agreement has been signed and ownership of the namespace has been claimed.

**Comment by thorade** [comment]
Just a minor note and cross-link:
The extension is listed on open-vsx.org here:
https://open-vsx.org/extension/SimplyDanny/modelica
